version: "3"
services:
  strapi-db:
    container_name: strapi-db
    env_file: .env
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./data/.mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - strapi

networks:
  strapi:
    driver: bridge
